# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from movement_msgs/LipFeedBack.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class LipFeedBack(genpy.Message):
  _md5sum = "e610855409fd0666f178d132dd374e0d"
  _type = "movement_msgs/LipFeedBack"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header                header
geometry_msgs/Point   comPos
geometry_msgs/Point   comVel
geometry_msgs/Point   comAcc
geometry_msgs/Point   footStep
geometry_msgs/Point   footStepR
geometry_msgs/Point   zmp
int16                 footGround
int16                 footAir
int16                 wState



================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','comPos','comVel','comAcc','footStep','footStepR','zmp','footGround','footAir','wState']
  _slot_types = ['std_msgs/Header','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,comPos,comVel,comAcc,footStep,footStepR,zmp,footGround,footAir,wState

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LipFeedBack, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.comPos is None:
        self.comPos = geometry_msgs.msg.Point()
      if self.comVel is None:
        self.comVel = geometry_msgs.msg.Point()
      if self.comAcc is None:
        self.comAcc = geometry_msgs.msg.Point()
      if self.footStep is None:
        self.footStep = geometry_msgs.msg.Point()
      if self.footStepR is None:
        self.footStepR = geometry_msgs.msg.Point()
      if self.zmp is None:
        self.zmp = geometry_msgs.msg.Point()
      if self.footGround is None:
        self.footGround = 0
      if self.footAir is None:
        self.footAir = 0
      if self.wState is None:
        self.wState = 0
    else:
      self.header = std_msgs.msg.Header()
      self.comPos = geometry_msgs.msg.Point()
      self.comVel = geometry_msgs.msg.Point()
      self.comAcc = geometry_msgs.msg.Point()
      self.footStep = geometry_msgs.msg.Point()
      self.footStepR = geometry_msgs.msg.Point()
      self.zmp = geometry_msgs.msg.Point()
      self.footGround = 0
      self.footAir = 0
      self.wState = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d3h().pack(_x.comPos.x, _x.comPos.y, _x.comPos.z, _x.comVel.x, _x.comVel.y, _x.comVel.z, _x.comAcc.x, _x.comAcc.y, _x.comAcc.z, _x.footStep.x, _x.footStep.y, _x.footStep.z, _x.footStepR.x, _x.footStepR.y, _x.footStepR.z, _x.zmp.x, _x.zmp.y, _x.zmp.z, _x.footGround, _x.footAir, _x.wState))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.comPos is None:
        self.comPos = geometry_msgs.msg.Point()
      if self.comVel is None:
        self.comVel = geometry_msgs.msg.Point()
      if self.comAcc is None:
        self.comAcc = geometry_msgs.msg.Point()
      if self.footStep is None:
        self.footStep = geometry_msgs.msg.Point()
      if self.footStepR is None:
        self.footStepR = geometry_msgs.msg.Point()
      if self.zmp is None:
        self.zmp = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 150
      (_x.comPos.x, _x.comPos.y, _x.comPos.z, _x.comVel.x, _x.comVel.y, _x.comVel.z, _x.comAcc.x, _x.comAcc.y, _x.comAcc.z, _x.footStep.x, _x.footStep.y, _x.footStep.z, _x.footStepR.x, _x.footStepR.y, _x.footStepR.z, _x.zmp.x, _x.zmp.y, _x.zmp.z, _x.footGround, _x.footAir, _x.wState,) = _get_struct_18d3h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_18d3h().pack(_x.comPos.x, _x.comPos.y, _x.comPos.z, _x.comVel.x, _x.comVel.y, _x.comVel.z, _x.comAcc.x, _x.comAcc.y, _x.comAcc.z, _x.footStep.x, _x.footStep.y, _x.footStep.z, _x.footStepR.x, _x.footStepR.y, _x.footStepR.z, _x.zmp.x, _x.zmp.y, _x.zmp.z, _x.footGround, _x.footAir, _x.wState))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.comPos is None:
        self.comPos = geometry_msgs.msg.Point()
      if self.comVel is None:
        self.comVel = geometry_msgs.msg.Point()
      if self.comAcc is None:
        self.comAcc = geometry_msgs.msg.Point()
      if self.footStep is None:
        self.footStep = geometry_msgs.msg.Point()
      if self.footStepR is None:
        self.footStepR = geometry_msgs.msg.Point()
      if self.zmp is None:
        self.zmp = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 150
      (_x.comPos.x, _x.comPos.y, _x.comPos.z, _x.comVel.x, _x.comVel.y, _x.comVel.z, _x.comAcc.x, _x.comAcc.y, _x.comAcc.z, _x.footStep.x, _x.footStep.y, _x.footStep.z, _x.footStepR.x, _x.footStepR.y, _x.footStepR.z, _x.zmp.x, _x.zmp.y, _x.zmp.z, _x.footGround, _x.footAir, _x.wState,) = _get_struct_18d3h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18d3h = None
def _get_struct_18d3h():
    global _struct_18d3h
    if _struct_18d3h is None:
        _struct_18d3h = struct.Struct("<18d3h")
    return _struct_18d3h
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
