bool toGazebo
bool toRobot
bool scanMotors
bool getPID
bool getMotorPos
bool send2Motor
bool[] setTorque
int16  motorIds
bool fall
bool ping

---
movement_msgs/JointStateMsg motorState
movement_msgs/MotorPIDMsg   motorPID
int16[]                     ids
