// Generated by gencpp from file behaviour_msgs/ActionPanelSrvResponse.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_ACTIONPANELSRVRESPONSE_H
#define BEHAVIOUR_MSGS_MESSAGE_ACTIONPANELSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behaviour_msgs
{
template <class ContainerAllocator>
struct ActionPanelSrvResponse_
{
  typedef ActionPanelSrvResponse_<ContainerAllocator> Type;

  ActionPanelSrvResponse_()
    : status(false)  {
    }
  ActionPanelSrvResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ActionPanelSrvResponse_

typedef ::behaviour_msgs::ActionPanelSrvResponse_<std::allocator<void> > ActionPanelSrvResponse;

typedef boost::shared_ptr< ::behaviour_msgs::ActionPanelSrvResponse > ActionPanelSrvResponsePtr;
typedef boost::shared_ptr< ::behaviour_msgs::ActionPanelSrvResponse const> ActionPanelSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator1> & lhs, const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator1> & lhs, const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour_msgs/ActionPanelSrvResponse";
  }

  static const char* value(const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionPanelSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour_msgs::ActionPanelSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_ACTIONPANELSRVRESPONSE_H
