// Generated by gencpp from file behaviour_msgs/ActionPanelSrvRequest.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_ACTIONPANELSRVREQUEST_H
#define BEHAVIOUR_MSGS_MESSAGE_ACTIONPANELSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <behaviour_msgs/ActionMsg.h>

namespace behaviour_msgs
{
template <class ContainerAllocator>
struct ActionPanelSrvRequest_
{
  typedef ActionPanelSrvRequest_<ContainerAllocator> Type;

  ActionPanelSrvRequest_()
    : actions()  {
    }
  ActionPanelSrvRequest_(const ContainerAllocator& _alloc)
    : actions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::behaviour_msgs::ActionMsg_<ContainerAllocator>  _actions_type;
  _actions_type actions;





  typedef boost::shared_ptr< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ActionPanelSrvRequest_

typedef ::behaviour_msgs::ActionPanelSrvRequest_<std::allocator<void> > ActionPanelSrvRequest;

typedef boost::shared_ptr< ::behaviour_msgs::ActionPanelSrvRequest > ActionPanelSrvRequestPtr;
typedef boost::shared_ptr< ::behaviour_msgs::ActionPanelSrvRequest const> ActionPanelSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator1> & lhs, const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.actions == rhs.actions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator1> & lhs, const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c602a34772abebfb14617e6bc6021cd0";
  }

  static const char* value(const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc602a34772abebfbULL;
  static const uint64_t static_value2 = 0x14617e6bc6021cd0ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour_msgs/ActionPanelSrvRequest";
  }

  static const char* value(const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour_msgs/ActionMsg actions\n"
"\n"
"\n"
"================================================================================\n"
"MSG: behaviour_msgs/ActionMsg\n"
"\n"
"bool ball_tracking\n"
"bool center_ball\n"
"bool align_body\n"
"bool walk\n"
"bool kick\n"
"int32 defend\n"
"bool squat\n"
"bool goal_tracking\n"
;
  }

  static const char* value(const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionPanelSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour_msgs::ActionPanelSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "actions: ";
    s << std::endl;
    Printer< ::behaviour_msgs::ActionMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.actions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_ACTIONPANELSRVREQUEST_H
