// Generated by gencpp from file behaviour_msgs/GameControllerSrv.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_GAMECONTROLLERSRV_H
#define BEHAVIOUR_MSGS_MESSAGE_GAMECONTROLLERSRV_H

#include <ros/service_traits.h>


#include <behaviour_msgs/GameControllerSrvRequest.h>
#include <behaviour_msgs/GameControllerSrvResponse.h>


namespace behaviour_msgs
{

struct GameControllerSrv
{

typedef GameControllerSrvRequest Request;
typedef GameControllerSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GameControllerSrv
} // namespace behaviour_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::behaviour_msgs::GameControllerSrv > {
  static const char* value()
  {
    return "55932133259e8c3335a553618447da45";
  }

  static const char* value(const ::behaviour_msgs::GameControllerSrv&) { return value(); }
};

template<>
struct DataType< ::behaviour_msgs::GameControllerSrv > {
  static const char* value()
  {
    return "behaviour_msgs/GameControllerSrv";
  }

  static const char* value(const ::behaviour_msgs::GameControllerSrv&) { return value(); }
};


// service_traits::MD5Sum< ::behaviour_msgs::GameControllerSrvRequest> should match
// service_traits::MD5Sum< ::behaviour_msgs::GameControllerSrv >
template<>
struct MD5Sum< ::behaviour_msgs::GameControllerSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::behaviour_msgs::GameControllerSrv >::value();
  }
  static const char* value(const ::behaviour_msgs::GameControllerSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::behaviour_msgs::GameControllerSrvRequest> should match
// service_traits::DataType< ::behaviour_msgs::GameControllerSrv >
template<>
struct DataType< ::behaviour_msgs::GameControllerSrvRequest>
{
  static const char* value()
  {
    return DataType< ::behaviour_msgs::GameControllerSrv >::value();
  }
  static const char* value(const ::behaviour_msgs::GameControllerSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::behaviour_msgs::GameControllerSrvResponse> should match
// service_traits::MD5Sum< ::behaviour_msgs::GameControllerSrv >
template<>
struct MD5Sum< ::behaviour_msgs::GameControllerSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::behaviour_msgs::GameControllerSrv >::value();
  }
  static const char* value(const ::behaviour_msgs::GameControllerSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::behaviour_msgs::GameControllerSrvResponse> should match
// service_traits::DataType< ::behaviour_msgs::GameControllerSrv >
template<>
struct DataType< ::behaviour_msgs::GameControllerSrvResponse>
{
  static const char* value()
  {
    return DataType< ::behaviour_msgs::GameControllerSrv >::value();
  }
  static const char* value(const ::behaviour_msgs::GameControllerSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_GAMECONTROLLERSRV_H
