// Generated by gencpp from file behaviour_msgs/service_page.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_SERVICE_PAGE_H
#define BEHAVIOUR_MSGS_MESSAGE_SERVICE_PAGE_H

#include <ros/service_traits.h>


#include <behaviour_msgs/service_pageRequest.h>
#include <behaviour_msgs/service_pageResponse.h>


namespace behaviour_msgs
{

struct service_page
{

typedef service_pageRequest Request;
typedef service_pageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct service_page
} // namespace behaviour_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::behaviour_msgs::service_page > {
  static const char* value()
  {
    return "e13299641855e63d2249efe085c03277";
  }

  static const char* value(const ::behaviour_msgs::service_page&) { return value(); }
};

template<>
struct DataType< ::behaviour_msgs::service_page > {
  static const char* value()
  {
    return "behaviour_msgs/service_page";
  }

  static const char* value(const ::behaviour_msgs::service_page&) { return value(); }
};


// service_traits::MD5Sum< ::behaviour_msgs::service_pageRequest> should match
// service_traits::MD5Sum< ::behaviour_msgs::service_page >
template<>
struct MD5Sum< ::behaviour_msgs::service_pageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::behaviour_msgs::service_page >::value();
  }
  static const char* value(const ::behaviour_msgs::service_pageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::behaviour_msgs::service_pageRequest> should match
// service_traits::DataType< ::behaviour_msgs::service_page >
template<>
struct DataType< ::behaviour_msgs::service_pageRequest>
{
  static const char* value()
  {
    return DataType< ::behaviour_msgs::service_page >::value();
  }
  static const char* value(const ::behaviour_msgs::service_pageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::behaviour_msgs::service_pageResponse> should match
// service_traits::MD5Sum< ::behaviour_msgs::service_page >
template<>
struct MD5Sum< ::behaviour_msgs::service_pageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::behaviour_msgs::service_page >::value();
  }
  static const char* value(const ::behaviour_msgs::service_pageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::behaviour_msgs::service_pageResponse> should match
// service_traits::DataType< ::behaviour_msgs::service_page >
template<>
struct DataType< ::behaviour_msgs::service_pageResponse>
{
  static const char* value()
  {
    return DataType< ::behaviour_msgs::service_page >::value();
  }
  static const char* value(const ::behaviour_msgs::service_pageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_SERVICE_PAGE_H
