// Generated by gencpp from file behaviour_msgs/service_pageRequest.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_SERVICE_PAGEREQUEST_H
#define BEHAVIOUR_MSGS_MESSAGE_SERVICE_PAGEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behaviour_msgs
{
template <class ContainerAllocator>
struct service_pageRequest_
{
  typedef service_pageRequest_<ContainerAllocator> Type;

  service_pageRequest_()
    : page()  {
    }
  service_pageRequest_(const ContainerAllocator& _alloc)
    : page(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _page_type;
  _page_type page;





  typedef boost::shared_ptr< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct service_pageRequest_

typedef ::behaviour_msgs::service_pageRequest_<std::allocator<void> > service_pageRequest;

typedef boost::shared_ptr< ::behaviour_msgs::service_pageRequest > service_pageRequestPtr;
typedef boost::shared_ptr< ::behaviour_msgs::service_pageRequest const> service_pageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour_msgs::service_pageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour_msgs::service_pageRequest_<ContainerAllocator1> & lhs, const ::behaviour_msgs::service_pageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.page == rhs.page;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour_msgs::service_pageRequest_<ContainerAllocator1> & lhs, const ::behaviour_msgs::service_pageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25b28a799524944e4ad8b7de784a2cad";
  }

  static const char* value(const ::behaviour_msgs::service_pageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25b28a799524944eULL;
  static const uint64_t static_value2 = 0x4ad8b7de784a2cadULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour_msgs/service_pageRequest";
  }

  static const char* value(const ::behaviour_msgs::service_pageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string page\n"
;
  }

  static const char* value(const ::behaviour_msgs::service_pageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.page);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct service_pageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour_msgs::service_pageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour_msgs::service_pageRequest_<ContainerAllocator>& v)
  {
    s << indent << "page: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.page);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_SERVICE_PAGEREQUEST_H
