// Generated by gencpp from file behaviour_msgs/simMovMsg.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_SIMMOVMSG_H
#define BEHAVIOUR_MSGS_MESSAGE_SIMMOVMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behaviour_msgs
{
template <class ContainerAllocator>
struct simMovMsg_
{
  typedef simMovMsg_<ContainerAllocator> Type;

  simMovMsg_()
    : positions()  {
      positions.assign(0.0);
  }
  simMovMsg_(const ContainerAllocator& _alloc)
    : positions()  {
  (void)_alloc;
      positions.assign(0.0);
  }



   typedef boost::array<double, 2>  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::behaviour_msgs::simMovMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour_msgs::simMovMsg_<ContainerAllocator> const> ConstPtr;

}; // struct simMovMsg_

typedef ::behaviour_msgs::simMovMsg_<std::allocator<void> > simMovMsg;

typedef boost::shared_ptr< ::behaviour_msgs::simMovMsg > simMovMsgPtr;
typedef boost::shared_ptr< ::behaviour_msgs::simMovMsg const> simMovMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour_msgs::simMovMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour_msgs::simMovMsg_<ContainerAllocator1> & lhs, const ::behaviour_msgs::simMovMsg_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour_msgs::simMovMsg_<ContainerAllocator1> & lhs, const ::behaviour_msgs::simMovMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::simMovMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::simMovMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::simMovMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ea60a9dc19d0a4ca4c6af232a5cfe7f";
  }

  static const char* value(const ::behaviour_msgs::simMovMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ea60a9dc19d0a4cULL;
  static const uint64_t static_value2 = 0xa4c6af232a5cfe7fULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour_msgs/simMovMsg";
  }

  static const char* value(const ::behaviour_msgs::simMovMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[2] positions\n"
;
  }

  static const char* value(const ::behaviour_msgs::simMovMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simMovMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour_msgs::simMovMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour_msgs::simMovMsg_<ContainerAllocator>& v)
  {
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_SIMMOVMSG_H
