// Generated by gencpp from file behaviour_msgs/yamlTransitionSrv.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_YAMLTRANSITIONSRV_H
#define BEHAVIOUR_MSGS_MESSAGE_YAMLTRANSITIONSRV_H

#include <ros/service_traits.h>


#include <behaviour_msgs/yamlTransitionSrvRequest.h>
#include <behaviour_msgs/yamlTransitionSrvResponse.h>


namespace behaviour_msgs
{

struct yamlTransitionSrv
{

typedef yamlTransitionSrvRequest Request;
typedef yamlTransitionSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct yamlTransitionSrv
} // namespace behaviour_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::behaviour_msgs::yamlTransitionSrv > {
  static const char* value()
  {
    return "74ae6a711767847beb795a6d289ea68e";
  }

  static const char* value(const ::behaviour_msgs::yamlTransitionSrv&) { return value(); }
};

template<>
struct DataType< ::behaviour_msgs::yamlTransitionSrv > {
  static const char* value()
  {
    return "behaviour_msgs/yamlTransitionSrv";
  }

  static const char* value(const ::behaviour_msgs::yamlTransitionSrv&) { return value(); }
};


// service_traits::MD5Sum< ::behaviour_msgs::yamlTransitionSrvRequest> should match
// service_traits::MD5Sum< ::behaviour_msgs::yamlTransitionSrv >
template<>
struct MD5Sum< ::behaviour_msgs::yamlTransitionSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::behaviour_msgs::yamlTransitionSrv >::value();
  }
  static const char* value(const ::behaviour_msgs::yamlTransitionSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::behaviour_msgs::yamlTransitionSrvRequest> should match
// service_traits::DataType< ::behaviour_msgs::yamlTransitionSrv >
template<>
struct DataType< ::behaviour_msgs::yamlTransitionSrvRequest>
{
  static const char* value()
  {
    return DataType< ::behaviour_msgs::yamlTransitionSrv >::value();
  }
  static const char* value(const ::behaviour_msgs::yamlTransitionSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::behaviour_msgs::yamlTransitionSrvResponse> should match
// service_traits::MD5Sum< ::behaviour_msgs::yamlTransitionSrv >
template<>
struct MD5Sum< ::behaviour_msgs::yamlTransitionSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::behaviour_msgs::yamlTransitionSrv >::value();
  }
  static const char* value(const ::behaviour_msgs::yamlTransitionSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::behaviour_msgs::yamlTransitionSrvResponse> should match
// service_traits::DataType< ::behaviour_msgs::yamlTransitionSrv >
template<>
struct DataType< ::behaviour_msgs::yamlTransitionSrvResponse>
{
  static const char* value()
  {
    return DataType< ::behaviour_msgs::yamlTransitionSrv >::value();
  }
  static const char* value(const ::behaviour_msgs::yamlTransitionSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_YAMLTRANSITIONSRV_H
