// Generated by gencpp from file behaviour_msgs/yamlTransitionSrvRequest.msg
// DO NOT EDIT!


#ifndef BEHAVIOUR_MSGS_MESSAGE_YAMLTRANSITIONSRVREQUEST_H
#define BEHAVIOUR_MSGS_MESSAGE_YAMLTRANSITIONSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behaviour_msgs
{
template <class ContainerAllocator>
struct yamlTransitionSrvRequest_
{
  typedef yamlTransitionSrvRequest_<ContainerAllocator> Type;

  yamlTransitionSrvRequest_()
    : decision()  {
    }
  yamlTransitionSrvRequest_(const ContainerAllocator& _alloc)
    : decision(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _decision_type;
  _decision_type decision;





  typedef boost::shared_ptr< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct yamlTransitionSrvRequest_

typedef ::behaviour_msgs::yamlTransitionSrvRequest_<std::allocator<void> > yamlTransitionSrvRequest;

typedef boost::shared_ptr< ::behaviour_msgs::yamlTransitionSrvRequest > yamlTransitionSrvRequestPtr;
typedef boost::shared_ptr< ::behaviour_msgs::yamlTransitionSrvRequest const> yamlTransitionSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator1> & lhs, const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.decision == rhs.decision;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator1> & lhs, const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behaviour_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87ff97832d5405e41358fe1b7204e781";
  }

  static const char* value(const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87ff97832d5405e4ULL;
  static const uint64_t static_value2 = 0x1358fe1b7204e781ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behaviour_msgs/yamlTransitionSrvRequest";
  }

  static const char* value(const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string decision\n"
;
  }

  static const char* value(const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.decision);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yamlTransitionSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behaviour_msgs::yamlTransitionSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "decision: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.decision);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOUR_MSGS_MESSAGE_YAMLTRANSITIONSRVREQUEST_H
