(cl:defpackage behaviour_msgs-msg
  (:use )
  (:export
   "<ACTIONMSG>"
   "ACTIONMSG"
   "<GAMECONTROLLERMSG>"
   "GAMECONTROLLERMSG"
   "<GAMECONTROLLERPLAYERMSG>"
   "GAMECONTROLLERPLAYERMSG"
   "<GAMECONTROLLERTEAMMSG>"
   "GAMECONTROLLERTEAMMSG"
   "<GAMESTATE>"
   "GAMESTATE"
   "<PIDHEADMSG>"
   "PIDHEADMSG"
   "<STATEMACHINEACTIONSMSG>"
   "STATEMACHINEACTIONSMSG"
   "<SIMMOVMSG>"
   "SIMMOVMSG"
  ))

