(cl:defpackage movement_msgs-srv
  (:use )
  (:export
   "APPROVEDMOVEMENTSRV"
   "<APPROVEDMOVEMENTSRV-REQUEST>"
   "APPROVEDMOVEMENTSRV-REQUEST"
   "<APPROVEDMOVEMENTSRV-RESPONSE>"
   "APPROVEDMOVEMENTSRV-RESPONSE"
   "BEHREQUESTSRV"
   "<BEHREQUESTSRV-REQUEST>"
   "BEHREQUESTSRV-REQUEST"
   "<BEHREQUESTSRV-RESPONSE>"
   "BEHREQUESTSRV-RESPONSE"
   "COMMANDTOOPENCMSRV"
   "<COMMANDTOOPENCMSRV-REQUEST>"
   "COMMANDTOOPENCMSRV-REQUEST"
   "<COMMANDTOOPENCMSRV-RESPONSE>"
   "COMMANDTOOPENCMSRV-RESPONSE"
   "WALKCREATORREQUESTSRV"
   "<WALKCREATORREQUESTSRV-REQUEST>"
   "WALKCREATORREQUESTSRV-REQUEST"
   "<WALKCREATORREQUESTSRV-RESPONSE>"
   "WALKCREATORREQUESTSRV-RESPONSE"
  ))

