(cl:in-package movement_msgs-srv)
(cl:export '(GET_PARAMS-VAL
          GET_PARAMS
          ZCCORR-VAL
          ZCCORR
          TS-VAL
          TS
          TD-VAL
          TD
          STEPH-VAL
          STEPH
          ZCCORR-VAL
          ZCCORR
          TS-VAL
          TS
          TD-VAL
          TD
          STEPH-VAL
          STEPH
          DELAYR-VAL
          DELAYR
          DELAYL-VAL
          DELAYL
          DELAYALL-VAL
          DELAYALL
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
))