// Generated by gencpp from file movement_msgs/BehRequestInterface.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_BEHREQUESTINTERFACE_H
#define MOVEMENT_MSGS_MESSAGE_BEHREQUESTINTERFACE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct BehRequestInterface_
{
  typedef BehRequestInterface_<ContainerAllocator> Type;

  BehRequestInterface_()
    : required_movement()
    , required_status(false)  {
    }
  BehRequestInterface_(const ContainerAllocator& _alloc)
    : required_movement(_alloc)
    , required_status(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _required_movement_type;
  _required_movement_type required_movement;

   typedef uint8_t _required_status_type;
  _required_status_type required_status;





  typedef boost::shared_ptr< ::movement_msgs::BehRequestInterface_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::BehRequestInterface_<ContainerAllocator> const> ConstPtr;

}; // struct BehRequestInterface_

typedef ::movement_msgs::BehRequestInterface_<std::allocator<void> > BehRequestInterface;

typedef boost::shared_ptr< ::movement_msgs::BehRequestInterface > BehRequestInterfacePtr;
typedef boost::shared_ptr< ::movement_msgs::BehRequestInterface const> BehRequestInterfaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::BehRequestInterface_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::BehRequestInterface_<ContainerAllocator1> & lhs, const ::movement_msgs::BehRequestInterface_<ContainerAllocator2> & rhs)
{
  return lhs.required_movement == rhs.required_movement &&
    lhs.required_status == rhs.required_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::BehRequestInterface_<ContainerAllocator1> & lhs, const ::movement_msgs::BehRequestInterface_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::BehRequestInterface_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::BehRequestInterface_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::BehRequestInterface_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8e8e1d113594f935b637fde0165e779";
  }

  static const char* value(const ::movement_msgs::BehRequestInterface_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8e8e1d113594f93ULL;
  static const uint64_t static_value2 = 0x5b637fde0165e779ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/BehRequestInterface";
  }

  static const char* value(const ::movement_msgs::BehRequestInterface_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string required_movement\n"
"bool required_status\n"
;
  }

  static const char* value(const ::movement_msgs::BehRequestInterface_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.required_movement);
      stream.next(m.required_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehRequestInterface_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::BehRequestInterface_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::BehRequestInterface_<ContainerAllocator>& v)
  {
    s << indent << "required_movement: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.required_movement);
    s << indent << "required_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.required_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_BEHREQUESTINTERFACE_H
