// Generated by gencpp from file movement_msgs/DynamixelCreatorSrv.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_DYNAMIXELCREATORSRV_H
#define MOVEMENT_MSGS_MESSAGE_DYNAMIXELCREATORSRV_H

#include <ros/service_traits.h>


#include <movement_msgs/DynamixelCreatorSrvRequest.h>
#include <movement_msgs/DynamixelCreatorSrvResponse.h>


namespace movement_msgs
{

struct DynamixelCreatorSrv
{

typedef DynamixelCreatorSrvRequest Request;
typedef DynamixelCreatorSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DynamixelCreatorSrv
} // namespace movement_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_msgs::DynamixelCreatorSrv > {
  static const char* value()
  {
    return "afc4a102e69ac104a3346382d7f6e9b9";
  }

  static const char* value(const ::movement_msgs::DynamixelCreatorSrv&) { return value(); }
};

template<>
struct DataType< ::movement_msgs::DynamixelCreatorSrv > {
  static const char* value()
  {
    return "movement_msgs/DynamixelCreatorSrv";
  }

  static const char* value(const ::movement_msgs::DynamixelCreatorSrv&) { return value(); }
};


// service_traits::MD5Sum< ::movement_msgs::DynamixelCreatorSrvRequest> should match
// service_traits::MD5Sum< ::movement_msgs::DynamixelCreatorSrv >
template<>
struct MD5Sum< ::movement_msgs::DynamixelCreatorSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::DynamixelCreatorSrv >::value();
  }
  static const char* value(const ::movement_msgs::DynamixelCreatorSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::DynamixelCreatorSrvRequest> should match
// service_traits::DataType< ::movement_msgs::DynamixelCreatorSrv >
template<>
struct DataType< ::movement_msgs::DynamixelCreatorSrvRequest>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::DynamixelCreatorSrv >::value();
  }
  static const char* value(const ::movement_msgs::DynamixelCreatorSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_msgs::DynamixelCreatorSrvResponse> should match
// service_traits::MD5Sum< ::movement_msgs::DynamixelCreatorSrv >
template<>
struct MD5Sum< ::movement_msgs::DynamixelCreatorSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::DynamixelCreatorSrv >::value();
  }
  static const char* value(const ::movement_msgs::DynamixelCreatorSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::DynamixelCreatorSrvResponse> should match
// service_traits::DataType< ::movement_msgs::DynamixelCreatorSrv >
template<>
struct DataType< ::movement_msgs::DynamixelCreatorSrvResponse>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::DynamixelCreatorSrv >::value();
  }
  static const char* value(const ::movement_msgs::DynamixelCreatorSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_DYNAMIXELCREATORSRV_H
