// Generated by gencpp from file movement_msgs/LipCtrlSrv.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_LIPCTRLSRV_H
#define MOVEMENT_MSGS_MESSAGE_LIPCTRLSRV_H

#include <ros/service_traits.h>


#include <movement_msgs/LipCtrlSrvRequest.h>
#include <movement_msgs/LipCtrlSrvResponse.h>


namespace movement_msgs
{

struct LipCtrlSrv
{

typedef LipCtrlSrvRequest Request;
typedef LipCtrlSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LipCtrlSrv
} // namespace movement_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_msgs::LipCtrlSrv > {
  static const char* value()
  {
    return "19f7b1da62232e35c765032ea5c2cdaa";
  }

  static const char* value(const ::movement_msgs::LipCtrlSrv&) { return value(); }
};

template<>
struct DataType< ::movement_msgs::LipCtrlSrv > {
  static const char* value()
  {
    return "movement_msgs/LipCtrlSrv";
  }

  static const char* value(const ::movement_msgs::LipCtrlSrv&) { return value(); }
};


// service_traits::MD5Sum< ::movement_msgs::LipCtrlSrvRequest> should match
// service_traits::MD5Sum< ::movement_msgs::LipCtrlSrv >
template<>
struct MD5Sum< ::movement_msgs::LipCtrlSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::LipCtrlSrv >::value();
  }
  static const char* value(const ::movement_msgs::LipCtrlSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::LipCtrlSrvRequest> should match
// service_traits::DataType< ::movement_msgs::LipCtrlSrv >
template<>
struct DataType< ::movement_msgs::LipCtrlSrvRequest>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::LipCtrlSrv >::value();
  }
  static const char* value(const ::movement_msgs::LipCtrlSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_msgs::LipCtrlSrvResponse> should match
// service_traits::MD5Sum< ::movement_msgs::LipCtrlSrv >
template<>
struct MD5Sum< ::movement_msgs::LipCtrlSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::LipCtrlSrv >::value();
  }
  static const char* value(const ::movement_msgs::LipCtrlSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::LipCtrlSrvResponse> should match
// service_traits::DataType< ::movement_msgs::LipCtrlSrv >
template<>
struct DataType< ::movement_msgs::LipCtrlSrvResponse>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::LipCtrlSrv >::value();
  }
  static const char* value(const ::movement_msgs::LipCtrlSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_LIPCTRLSRV_H
