// Generated by gencpp from file movement_msgs/LipCtrlSrvResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_LIPCTRLSRVRESPONSE_H
#define MOVEMENT_MSGS_MESSAGE_LIPCTRLSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct LipCtrlSrvResponse_
{
  typedef LipCtrlSrvResponse_<ContainerAllocator> Type;

  LipCtrlSrvResponse_()
    {
    }
  LipCtrlSrvResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LipCtrlSrvResponse_

typedef ::movement_msgs::LipCtrlSrvResponse_<std::allocator<void> > LipCtrlSrvResponse;

typedef boost::shared_ptr< ::movement_msgs::LipCtrlSrvResponse > LipCtrlSrvResponsePtr;
typedef boost::shared_ptr< ::movement_msgs::LipCtrlSrvResponse const> LipCtrlSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/LipCtrlSrvResponse";
  }

  static const char* value(const ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"\n"
;
  }

  static const char* value(const ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LipCtrlSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::movement_msgs::LipCtrlSrvResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_LIPCTRLSRVRESPONSE_H
