// Generated by gencpp from file movement_msgs/LoadHumanoidPropertiesSrvResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_LOADHUMANOIDPROPERTIESSRVRESPONSE_H
#define MOVEMENT_MSGS_MESSAGE_LOADHUMANOIDPROPERTIESSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace movement_msgs
{
template <class ContainerAllocator>
struct LoadHumanoidPropertiesSrvResponse_
{
  typedef LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> Type;

  LoadHumanoidPropertiesSrvResponse_()
    : zmpPoint()
    , comPoint()
    , footComPoint()
    , torq()  {
    }
  LoadHumanoidPropertiesSrvResponse_(const ContainerAllocator& _alloc)
    : zmpPoint(_alloc)
    , comPoint(_alloc)
    , footComPoint(_alloc)
    , torq(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _zmpPoint_type;
  _zmpPoint_type zmpPoint;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _comPoint_type;
  _comPoint_type comPoint;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _footComPoint_type;
  _footComPoint_type footComPoint;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _torq_type;
  _torq_type torq;





  typedef boost::shared_ptr< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LoadHumanoidPropertiesSrvResponse_

typedef ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<std::allocator<void> > LoadHumanoidPropertiesSrvResponse;

typedef boost::shared_ptr< ::movement_msgs::LoadHumanoidPropertiesSrvResponse > LoadHumanoidPropertiesSrvResponsePtr;
typedef boost::shared_ptr< ::movement_msgs::LoadHumanoidPropertiesSrvResponse const> LoadHumanoidPropertiesSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.zmpPoint == rhs.zmpPoint &&
    lhs.comPoint == rhs.comPoint &&
    lhs.footComPoint == rhs.footComPoint &&
    lhs.torq == rhs.torq;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7a33232467fc746c475c5575da5109a";
  }

  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7a33232467fc746ULL;
  static const uint64_t static_value2 = 0xc475c5575da5109aULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/LoadHumanoidPropertiesSrvResponse";
  }

  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"geometry_msgs/Point  zmpPoint\n"
"geometry_msgs/Point  comPoint\n"
"geometry_msgs/Point  footComPoint\n"
"float64[]            torq\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zmpPoint);
      stream.next(m.comPoint);
      stream.next(m.footComPoint);
      stream.next(m.torq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadHumanoidPropertiesSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::LoadHumanoidPropertiesSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "zmpPoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.zmpPoint);
    s << indent << "comPoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.comPoint);
    s << indent << "footComPoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.footComPoint);
    s << indent << "torq[]" << std::endl;
    for (size_t i = 0; i < v.torq.size(); ++i)
    {
      s << indent << "  torq[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.torq[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_LOADHUMANOIDPROPERTIESSRVRESPONSE_H
