// Generated by gencpp from file movement_msgs/LoadMapConfigsSrvResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_LOADMAPCONFIGSSRVRESPONSE_H
#define MOVEMENT_MSGS_MESSAGE_LOADMAPCONFIGSSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <movement_msgs/IDMapMsg.h>

namespace movement_msgs
{
template <class ContainerAllocator>
struct LoadMapConfigsSrvResponse_
{
  typedef LoadMapConfigsSrvResponse_<ContainerAllocator> Type;

  LoadMapConfigsSrvResponse_()
    : idMap()  {
    }
  LoadMapConfigsSrvResponse_(const ContainerAllocator& _alloc)
    : idMap(_alloc)  {
  (void)_alloc;
    }



   typedef  ::movement_msgs::IDMapMsg_<ContainerAllocator>  _idMap_type;
  _idMap_type idMap;





  typedef boost::shared_ptr< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LoadMapConfigsSrvResponse_

typedef ::movement_msgs::LoadMapConfigsSrvResponse_<std::allocator<void> > LoadMapConfigsSrvResponse;

typedef boost::shared_ptr< ::movement_msgs::LoadMapConfigsSrvResponse > LoadMapConfigsSrvResponsePtr;
typedef boost::shared_ptr< ::movement_msgs::LoadMapConfigsSrvResponse const> LoadMapConfigsSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.idMap == rhs.idMap;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23b63436cd0e468319455113fa36e5ec";
  }

  static const char* value(const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23b63436cd0e4683ULL;
  static const uint64_t static_value2 = 0x19455113fa36e5ecULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/LoadMapConfigsSrvResponse";
  }

  static const char* value(const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"movement_msgs/IDMapMsg  idMap\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: movement_msgs/IDMapMsg\n"
"Header                    header\n"
"std_msgs/Int32MultiArray  map\n"
"string[]                  jNames\n"
"int32                     robotDOF\n"
"int32                     urdfDOF\n"
"int32                     ikDOF\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Int32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"int32[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idMap);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadMapConfigsSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::LoadMapConfigsSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "idMap: ";
    s << std::endl;
    Printer< ::movement_msgs::IDMapMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.idMap);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_LOADMAPCONFIGSSRVRESPONSE_H
