// Generated by gencpp from file movement_msgs/LoadHumanoidPropertiesSrv.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_LOADHUMANOIDPROPERTIESSRV_H
#define MOVEMENT_MSGS_MESSAGE_LOADHUMANOIDPROPERTIESSRV_H

#include <ros/service_traits.h>


#include <movement_msgs/LoadHumanoidPropertiesSrvRequest.h>
#include <movement_msgs/LoadHumanoidPropertiesSrvResponse.h>


namespace movement_msgs
{

struct LoadHumanoidPropertiesSrv
{

typedef LoadHumanoidPropertiesSrvRequest Request;
typedef LoadHumanoidPropertiesSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadHumanoidPropertiesSrv
} // namespace movement_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrv > {
  static const char* value()
  {
    return "3e2b196ffde962aa21d86738ea07bc83";
  }

  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrv&) { return value(); }
};

template<>
struct DataType< ::movement_msgs::LoadHumanoidPropertiesSrv > {
  static const char* value()
  {
    return "movement_msgs/LoadHumanoidPropertiesSrv";
  }

  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrv&) { return value(); }
};


// service_traits::MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrvRequest> should match
// service_traits::MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrv >
template<>
struct MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrv >::value();
  }
  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::LoadHumanoidPropertiesSrvRequest> should match
// service_traits::DataType< ::movement_msgs::LoadHumanoidPropertiesSrv >
template<>
struct DataType< ::movement_msgs::LoadHumanoidPropertiesSrvRequest>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::LoadHumanoidPropertiesSrv >::value();
  }
  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrvResponse> should match
// service_traits::MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrv >
template<>
struct MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::LoadHumanoidPropertiesSrv >::value();
  }
  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::LoadHumanoidPropertiesSrvResponse> should match
// service_traits::DataType< ::movement_msgs::LoadHumanoidPropertiesSrv >
template<>
struct DataType< ::movement_msgs::LoadHumanoidPropertiesSrvResponse>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::LoadHumanoidPropertiesSrv >::value();
  }
  static const char* value(const ::movement_msgs::LoadHumanoidPropertiesSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_LOADHUMANOIDPROPERTIESSRV_H
