// Generated by gencpp from file movement_msgs/MotorStateMsg.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_MOTORSTATEMSG_H
#define MOVEMENT_MSGS_MESSAGE_MOTORSTATEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace movement_msgs
{
template <class ContainerAllocator>
struct MotorStateMsg_
{
  typedef MotorStateMsg_<ContainerAllocator> Type;

  MotorStateMsg_()
    : header()
    , temp()
    , error()  {
    }
  MotorStateMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temp(_alloc)
    , error(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _temp_type;
  _temp_type temp;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::movement_msgs::MotorStateMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::MotorStateMsg_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStateMsg_

typedef ::movement_msgs::MotorStateMsg_<std::allocator<void> > MotorStateMsg;

typedef boost::shared_ptr< ::movement_msgs::MotorStateMsg > MotorStateMsgPtr;
typedef boost::shared_ptr< ::movement_msgs::MotorStateMsg const> MotorStateMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::MotorStateMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::MotorStateMsg_<ContainerAllocator1> & lhs, const ::movement_msgs::MotorStateMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.temp == rhs.temp &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::MotorStateMsg_<ContainerAllocator1> & lhs, const ::movement_msgs::MotorStateMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::MotorStateMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::MotorStateMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::MotorStateMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "482b5a95d66b7eabefdb77851294e15c";
  }

  static const char* value(const ::movement_msgs::MotorStateMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x482b5a95d66b7eabULL;
  static const uint64_t static_value2 = 0xefdb77851294e15cULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/MotorStateMsg";
  }

  static const char* value(const ::movement_msgs::MotorStateMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header     header\n"
"float64[]  temp\n"
"int16[]    error\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::movement_msgs::MotorStateMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temp);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorStateMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::MotorStateMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::MotorStateMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temp[]" << std::endl;
    for (size_t i = 0; i < v.temp.size(); ++i)
    {
      s << indent << "  temp[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.temp[i]);
    }
    s << indent << "error[]" << std::endl;
    for (size_t i = 0; i < v.error.size(); ++i)
    {
      s << indent << "  error[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.error[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_MOTORSTATEMSG_H
