// Generated by gencpp from file movement_msgs/MotorSetSrv.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_MOTORSETSRV_H
#define MOVEMENT_MSGS_MESSAGE_MOTORSETSRV_H

#include <ros/service_traits.h>


#include <movement_msgs/MotorSetSrvRequest.h>
#include <movement_msgs/MotorSetSrvResponse.h>


namespace movement_msgs
{

struct MotorSetSrv
{

typedef MotorSetSrvRequest Request;
typedef MotorSetSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorSetSrv
} // namespace movement_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::movement_msgs::MotorSetSrv > {
  static const char* value()
  {
    return "ec1859e255b743457ecbab4cc3de4b47";
  }

  static const char* value(const ::movement_msgs::MotorSetSrv&) { return value(); }
};

template<>
struct DataType< ::movement_msgs::MotorSetSrv > {
  static const char* value()
  {
    return "movement_msgs/MotorSetSrv";
  }

  static const char* value(const ::movement_msgs::MotorSetSrv&) { return value(); }
};


// service_traits::MD5Sum< ::movement_msgs::MotorSetSrvRequest> should match
// service_traits::MD5Sum< ::movement_msgs::MotorSetSrv >
template<>
struct MD5Sum< ::movement_msgs::MotorSetSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::MotorSetSrv >::value();
  }
  static const char* value(const ::movement_msgs::MotorSetSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::MotorSetSrvRequest> should match
// service_traits::DataType< ::movement_msgs::MotorSetSrv >
template<>
struct DataType< ::movement_msgs::MotorSetSrvRequest>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::MotorSetSrv >::value();
  }
  static const char* value(const ::movement_msgs::MotorSetSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::movement_msgs::MotorSetSrvResponse> should match
// service_traits::MD5Sum< ::movement_msgs::MotorSetSrv >
template<>
struct MD5Sum< ::movement_msgs::MotorSetSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::movement_msgs::MotorSetSrv >::value();
  }
  static const char* value(const ::movement_msgs::MotorSetSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::movement_msgs::MotorSetSrvResponse> should match
// service_traits::DataType< ::movement_msgs::MotorSetSrv >
template<>
struct DataType< ::movement_msgs::MotorSetSrvResponse>
{
  static const char* value()
  {
    return DataType< ::movement_msgs::MotorSetSrv >::value();
  }
  static const char* value(const ::movement_msgs::MotorSetSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_MOTORSETSRV_H
