// Generated by gencpp from file movement_msgs/MovementSrvResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_MOVEMENTSRVRESPONSE_H
#define MOVEMENT_MSGS_MESSAGE_MOVEMENTSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct MovementSrvResponse_
{
  typedef MovementSrvResponse_<ContainerAllocator> Type;

  MovementSrvResponse_()
    : confirmation()
    , path()  {
    }
  MovementSrvResponse_(const ContainerAllocator& _alloc)
    : confirmation(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _confirmation_type;
  _confirmation_type confirmation;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MovementSrvResponse_

typedef ::movement_msgs::MovementSrvResponse_<std::allocator<void> > MovementSrvResponse;

typedef boost::shared_ptr< ::movement_msgs::MovementSrvResponse > MovementSrvResponsePtr;
typedef boost::shared_ptr< ::movement_msgs::MovementSrvResponse const> MovementSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::MovementSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::MovementSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::MovementSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.confirmation == rhs.confirmation &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::MovementSrvResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::MovementSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "542fc7537a8cde71530b57eeb1e6ef8d";
  }

  static const char* value(const ::movement_msgs::MovementSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x542fc7537a8cde71ULL;
  static const uint64_t static_value2 = 0x530b57eeb1e6ef8dULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/MovementSrvResponse";
  }

  static const char* value(const ::movement_msgs::MovementSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string 		     confirmation\n"
"string			     path\n"
"\n"
;
  }

  static const char* value(const ::movement_msgs::MovementSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confirmation);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovementSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::MovementSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::MovementSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "confirmation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.confirmation);
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_MOVEMENTSRVRESPONSE_H
