// Generated by gencpp from file movement_msgs/OpenCmResponse.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_OPENCMRESPONSE_H
#define MOVEMENT_MSGS_MESSAGE_OPENCMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct OpenCmResponse_
{
  typedef OpenCmResponse_<ContainerAllocator> Type;

  OpenCmResponse_()
    : result()  {
    }
  OpenCmResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::movement_msgs::OpenCmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::OpenCmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OpenCmResponse_

typedef ::movement_msgs::OpenCmResponse_<std::allocator<void> > OpenCmResponse;

typedef boost::shared_ptr< ::movement_msgs::OpenCmResponse > OpenCmResponsePtr;
typedef boost::shared_ptr< ::movement_msgs::OpenCmResponse const> OpenCmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::OpenCmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::OpenCmResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::OpenCmResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::OpenCmResponse_<ContainerAllocator1> & lhs, const ::movement_msgs::OpenCmResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::OpenCmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::OpenCmResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::OpenCmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f28a43bd8260b5272cff437c9698b1e";
  }

  static const char* value(const ::movement_msgs::OpenCmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f28a43bd8260b52ULL;
  static const uint64_t static_value2 = 0x72cff437c9698b1eULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/OpenCmResponse";
  }

  static const char* value(const ::movement_msgs::OpenCmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint16[] result\n"
"\n"
;
  }

  static const char* value(const ::movement_msgs::OpenCmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OpenCmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::OpenCmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::OpenCmResponse_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_OPENCMRESPONSE_H
