// Generated by gencpp from file movement_msgs/PredefinedMovementSrvRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_PREDEFINEDMOVEMENTSRVREQUEST_H
#define MOVEMENT_MSGS_MESSAGE_PREDEFINEDMOVEMENTSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct PredefinedMovementSrvRequest_
{
  typedef PredefinedMovementSrvRequest_<ContainerAllocator> Type;

  PredefinedMovementSrvRequest_()
    : request()  {
    }
  PredefinedMovementSrvRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PredefinedMovementSrvRequest_

typedef ::movement_msgs::PredefinedMovementSrvRequest_<std::allocator<void> > PredefinedMovementSrvRequest;

typedef boost::shared_ptr< ::movement_msgs::PredefinedMovementSrvRequest > PredefinedMovementSrvRequestPtr;
typedef boost::shared_ptr< ::movement_msgs::PredefinedMovementSrvRequest const> PredefinedMovementSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator1> & lhs, const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator1> & lhs, const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b13f31f7a0a36901919f7ec0d9f40d4";
  }

  static const char* value(const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b13f31f7a0a3690ULL;
  static const uint64_t static_value2 = 0x1919f7ec0d9f40d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/PredefinedMovementSrvRequest";
  }

  static const char* value(const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request\n"
"\n"
;
  }

  static const char* value(const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredefinedMovementSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::PredefinedMovementSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_PREDEFINEDMOVEMENTSRVREQUEST_H
