// Generated by gencpp from file movement_msgs/BehRequestSrvRequest.msg
// DO NOT EDIT!


#ifndef MOVEMENT_MSGS_MESSAGE_BEHREQUESTSRVREQUEST_H
#define MOVEMENT_MSGS_MESSAGE_BEHREQUESTSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace movement_msgs
{
template <class ContainerAllocator>
struct BehRequestSrvRequest_
{
  typedef BehRequestSrvRequest_<ContainerAllocator> Type;

  BehRequestSrvRequest_()
    : description()  {
    }
  BehRequestSrvRequest_(const ContainerAllocator& _alloc)
    : description(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BehRequestSrvRequest_

typedef ::movement_msgs::BehRequestSrvRequest_<std::allocator<void> > BehRequestSrvRequest;

typedef boost::shared_ptr< ::movement_msgs::BehRequestSrvRequest > BehRequestSrvRequestPtr;
typedef boost::shared_ptr< ::movement_msgs::BehRequestSrvRequest const> BehRequestSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator1> & lhs, const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.description == rhs.description;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator1> & lhs, const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace movement_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56a2040e58d4fe3f4d4a0df112eea2f6";
  }

  static const char* value(const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56a2040e58d4fe3fULL;
  static const uint64_t static_value2 = 0x4d4a0df112eea2f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movement_msgs/BehRequestSrvRequest";
  }

  static const char* value(const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string description\n"
"\n"
;
  }

  static const char* value(const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehRequestSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movement_msgs::BehRequestSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVEMENT_MSGS_MESSAGE_BEHREQUESTSRVREQUEST_H
