(cl:defpackage behaviour_msgs-srv
  (:use )
  (:export
   "ACTIONPANELSRV"
   "<ACTIONPANELSRV-REQUEST>"
   "ACTIONPANELSRV-REQUEST"
   "<ACTIONPANELSRV-RESPONSE>"
   "ACTIONPANELSRV-RESPONSE"
   "GAMECONTROLLERSRV"
   "<GAMECONTROLLERSRV-REQUEST>"
   "GAMECONTROLLERSRV-REQUEST"
   "<GAMECONTROLLERSRV-RESPONSE>"
   "GAMECONTROLLERSRV-RESPONSE"
   "SERVICE_PAGE"
   "<SERVICE_PAGE-REQUEST>"
   "SERVICE_PAGE-REQUEST"
   "<SERVICE_PAGE-RESPONSE>"
   "SERVICE_PAGE-RESPONSE"
   "YAMLTRANSITIONSRV"
   "<YAMLTRANSITIONSRV-REQUEST>"
   "YAMLTRANSITIONSRV-REQUEST"
   "<YAMLTRANSITIONSRV-RESPONSE>"
   "YAMLTRANSITIONSRV-RESPONSE"
  ))

