(cl:in-package modularized_bhv_msgs-msg)
(cl:export '(FALLSTATE-VAL
          FALLSTATE
          BALLFOUND-VAL
          BALLFOUND
          BALLCLOSE-VAL
          BALLCLOSE
          BALLRELATIVEPOSITION-VAL
          BALLRELATIVEPOSITION
          VERANGLEACCOMPLISHED-VAL
          VERANGLEACCOMPLISHED
          HEADPOSSIBLEMOVEMENTS-VAL
          HEADPOSSIBLEMOVEMENTS
          HORMOTOROUTOFCENTER-VAL
          HORMOTOROUTOFCENTER
          HORMOTORPOSITION-VAL
          HORMOTORPOSITION
))