(cl:defpackage movement_msgs-msg
  (:use )
  (:export
   "<HEADPARAMSMSG>"
   "HEADPARAMSMSG"
   "<OPENCMREQUESTMSG>"
   "OPENCMREQUESTMSG"
   "<OPENCMRESPONSEMSG>"
   "OPENCMRESPONSEMSG"
   "<WALKINGPARAMSMSG>"
   "WALKINGPARAMSMSG"
   "<WALKINGPOSITIONSMSG>"
   "WALKINGPOSITIONSMSG"
  ))

