(cl:in-package movement_msgs-msg)
(cl:export '(DATA-VAL
          DATA
          BINS-VAL
          BINS
          FREQ-VAL
          FREQ
          AMP-VAL
          AMP
          MEAN-VAL
          MEAN
          INTEGRAL-VAL
          INTEGRAL
          FREQREF-VAL
          FREQREF
          FREQRANGE-VAL
          FREQRANGE
          AMPREF-VAL
          AMPREF
          AMPRANGE-VAL
          AMPRANGE
          MEANREF-VAL
          MEANREF
          MEANRANGE-VAL
          MEANRANGE
          FREQPERF-VAL
          FREQPERF
          AMPPERF-VAL
          AMPPERF
          MEANPERF-VAL
          MEANPERF
          WFREQ-VAL
          WFREQ
          WAMP-VAL
          WAMP
          WMEAN-VAL
          WMEAN
          PERF-VAL
          PERF
))