(cl:in-package movement_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          RFOOT-VAL
          RFOOT
          LFOOT-VAL
          LFOOT
          FORCE-VAL
          FORCE
          TORQUE3-VAL
          TORQUE3
          TORQUE4-VAL
          TORQUE4
          TORQUEF-VAL
          TORQUEF
          IMU-VAL
          IMU
          PERF-VAL
          PERF
          DF-VAL
          DF
          STATE-VAL
          STATE
))