(cl:in-package movement_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          CTRL_FLAG-VAL
          CTRL_FLAG
          ARM_CTRL_FLAG-VAL
          ARM_CTRL_FLAG
          TORSO_CTRL_FLAG-VAL
          TORSO_CTRL_FLAG
          PHASE_CTRL_FLAG-VAL
          PHASE_CTRL_FLAG
          SLOPE_CTRL_FLAG-VAL
          SLOPE_CTRL_FLAG
          FOOT_CTRL_FLAG-VAL
          FOOT_CTRL_FLAG
          TORSOADDX-VAL
          TORSOADDX
          TORSOADDY-VAL
          TORSOADDY
          TORSOADDZ-VAL
          TORSOADDZ
          SLOPE-VAL
          SLOPE
          RFOOTFAC-VAL
          RFOOTFAC
          LFOOTFAC-VAL
          LFOOTFAC
          PHASEFAC-VAL
          PHASEFAC
          ARMADD-VAL
          ARMADD
          DELAYR-VAL
          DELAYR
          DELAYL-VAL
          DELAYL
          DELAYALL-VAL
          DELAYALL
))