(cl:in-package movement_msgs-msg)
(cl:export '(FIRST_POSE-VAL
          FIRST_POSE
          MOVE_HEAD-VAL
          MOVE_HEAD
          WALK_FLAG-VAL
          WALK_FLAG
          TEST_MODE-VAL
          TEST_MODE
          ZCCORR-VAL
          ZCCORR
          TS-VAL
          TS
          TD-VAL
          TD
          STEPH-VAL
          STEPH
          DELAYR-VAL
          DELAYR
          DELAYL-VAL
          DELAYL
          DELAYALL-VAL
          DELAYALL
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
))